/* generated by Svelte v3.38.3 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;